resolver: lts-20.6
extra-deps:
- pandoc-3.0
- skylighting-core-0.13.2
- skylighting-0.13.2
- skylighting-format-context-0.1.0.1
- skylighting-format-ansi-0.1
- skylighting-format-latex-0.1
- skylighting-format-blaze-html-0.1.1
- gridtables-0.1.0.0
- hslua-cli-1.2.0
- hslua-list-1.1.0
- hslua-module-text-1.0.3
- hslua-module-zip-1.0.0
- jira-wiki-markup-1.5.0
- mime-types-0.1.1.0
- doctemplates-0.11
- commonmark-extensions-0.2.3.3
- git: https://github.com/jgm/texmath
  commit: bd466e1f98d0916f2d6ff3779ee1a11674c27c89
- git: https://github.com/jgm/citeproc
  commit: 7e0a9a39811098577f037e12bd8a897e109e8753
- git: https://github.com/jgm/pandoc-types
  commit: 8c7bc6c66d22538711171b8cfd0e5f3d48de39fd
- git: https://github.com/pandoc/pandoc-lua-marshal
  commit: 76a568e98c424b1e35a80f26f5998136adbeb165
- git: https://github.com/jgm/commonmark-hs
  commit: 869bbce6b5e7e82bfce2ce36a38391176fb0fe4a
  subdirs: [commonmark-pandoc]
